SELECT ANIMAL_ID,ANIMAL_TYPE,NAME
FROM ANIMAL_OUTS 
WHERE ANIMAL_ID IN (
    SELECT ANIMAL_ID
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE "Intact%"
) 
AND SEX_UPON_OUTCOME NOT LIKE "Intact%"
ORDER BY ANIMAL_ID