-- 코드를 작성해주세요
SELECT I.ID, N.FISH_NAME,I.LENGTH
FROM FISH_INFO AS I
JOIN FISH_NAME_INFO AS N ON I.FISH_TYPE = N.FISH_TYPE
JOIN (SELECT MAX(LENGTH) AS LENGTH ,FISH_TYPE
      FROM FISH_INFO
      GROUP BY FISH_TYPE
      HAVING MAX(LENGTH)>10 ) 
      AS C 
      ON C.FISH_TYPE = I.FISH_TYPE AND C.LENGTH=I.LENGTH
ORDER BY I.ID
                  



                   